export const SHOW_LOADING_ACTION = 'base/SHOW_LOADING_ACTION';
export const HIDE_LOADING_ACTION = 'base/HIDE_LOADING_ACTION';

export const REQUEST_GET_SITE_BASIC_DATA = 'base/REQUEST_GET_SITE_BASIC_DATA';
export const SUCCEEDED_GET_SITE_BASIC_DATA = 'base/SUCCEEDED_GET_SITE_BASIC_DATA';
export const FAILED_GET_SITE_BASIC_DATA = 'base/FAILED_GET_SITE_BASIC_DATA';


export const INIT_LOGIN_DATA = 'base/INIT_LOGIN_DATA';
export const SUCCEEDED_INIT_LOGIN_DATA = 'base/SUCCEEDED_INIT_LOGIN_DATA';

export const REQUEST_GET_USER_BASIC_DATA = 'account/REQUEST_GET_USER_BASIC_DATA';
export const SUCCEEDED_GET_USER_BASIC_DATA = 'account/SUCCEEDED_GET_USER_BASIC_DATA';
export const FAILED_GET_USER_BASIC_DATA = 'account/FAILED_GET_USER_BASIC_DATA';

export const REQUEST_USER_ACCOUNT_BASIC_DATA = 'account/REQUEST_USER_ACCOUNT_BASIC_DATA';
export const SUCCEEDED_USER_ACCOUNT_BASIC_DATA = 'account/SUCCEEDED_USER_ACCOUNT_BASIC_DATA';
export const FAILED_USER_ACCOUNT_BASIC_DATA = 'account/FAILED_USER_ACCOUNT_BASIC_DATA';

export const INITIALT_TRY_LOGIN = 'auth/INITIALT_TRY_LOGIN';

export const REQUEST_TRY_LOGIN = 'auth/REQUEST_TRY_LOGIN';
export const SUCCEEDED_TRY_LOGIN = 'auth/SUCCEEDED_TRY_LOGIN';
export const FAILED_TRY_LOGIN = 'auth/FAILED_TRY_LOGIN';



export const REQUEST_GET_TIMELINE_LIST = 'profile/REQUEST_GET_TIMELINE_LIST';
export const SUCCEEDED_GET_TIMELINE_LIST = 'profile/SUCCEEDED_GET_TIMELINE_LIST';
export const FAILED_GET_TIMELINE_LIST = 'profile/FAILED_GET_TIMELINE_LIST';